package com.young.xshop.entity;

/**
 * Database Table Remarks:
 *   文件信息表
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table nx_system_file_info
 */
public class NxSystemFileInfo {
    /**
     * Database Column Remarks:
     *   主键
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nx_system_file_info.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     * Database Column Remarks:
     *   原始文件名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nx_system_file_info.origin_name
     *
     * @mbg.generated
     */
    private String originName;

    /**
     * Database Column Remarks:
     *   存储文件名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nx_system_file_info.file_name
     *
     * @mbg.generated
     */
    private String fileName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nx_system_file_info.id
     *
     * @return the value of nx_system_file_info.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nx_system_file_info.id
     *
     * @param id the value for nx_system_file_info.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nx_system_file_info.origin_name
     *
     * @return the value of nx_system_file_info.origin_name
     *
     * @mbg.generated
     */
    public String getOriginName() {
        return originName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nx_system_file_info.origin_name
     *
     * @param originName the value for nx_system_file_info.origin_name
     *
     * @mbg.generated
     */
    public void setOriginName(String originName) {
        this.originName = originName == null ? null : originName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nx_system_file_info.file_name
     *
     * @return the value of nx_system_file_info.file_name
     *
     * @mbg.generated
     */
    public String getFileName() {
        return fileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nx_system_file_info.file_name
     *
     * @param fileName the value for nx_system_file_info.file_name
     *
     * @mbg.generated
     */
    public void setFileName(String fileName) {
        this.fileName = fileName == null ? null : fileName.trim();
    }
}